### ISSUE TITLE
Fix `Uncaught DOMException: The play() request was interrupted by a call to pause()`

### ISSUE THREAD

**Issue by nitzel** [NoHatCoder/Playtak#12]
`VM5028 :1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22`
https://developers.google.com/web/updates/2017/06/play-request-was-interrupted

**To reproduce**
Load ptn
```
[Site "PlayTak.com"]
[Date "2021.2.3"]
[Player1 "You"]
[Player2 "You"]
[Size "5"]
[Result ""]

1. a3 e3
2. e2 a2
```

**Comment by NoHatCoder** [comment]
Except for the audio playing multiple times when loading a board, this is working pretty much as intended. The real problem is that browsers suddenly decided to create a promise that we don't need.

In any case, I don't think the calls to pause are necessary, I guess if we remove them the console spam will go away.
